frequency: 30  # Hz, update rate of EKF
sensor_timeout: 0.1  # Max time delay before ignoring a sensor

two_d_mode: false  # Set to true if ignoring Z-axis (not recommended for drones)
transform_time_offset: 0.0
transform_timeout: 0.0

# Set world frame and robot frame
world_frame: drone_frame             # Global reference frame
odom_frame: drone_frame              # Use the global frame since no dedicated odom frame is available
base_link_frame: apriltag_frame   # Drone is your base (or "base_link")

# Configure Pose Inputs
# First source: Transformed pose from tf2_listener.py
pose0: /transformed_pose
pose0_config: [true,  true,  true,
               true,  true,  true,
               false, false, false
               false, false, false
               false, false, false]
pose0_queue_size: 10
pose0_differential: true
#covariance: [0.05, 0.05, 0.05, 0.01, 0.01, 0.01]  # Adjust based on sensor reliability

# Second source: Apriltag detection pose
pose1: /apriltag/pose
pose1_config: [true,  true,  true,
               true,  true,  true,
               false, false, false
               false, false, false
               false, false, false]
pose1_queue_size: 10
#covariance: [0.1, 0.1, 0.1, 0.02, 0.02, 0.02]  # Adjust based on tag accuracy
