// Generated by gencpp from file anafi_control/TwistModified.msg
// DO NOT EDIT!


#ifndef ANAFI_CONTROL_MESSAGE_TWISTMODIFIED_H
#define ANAFI_CONTROL_MESSAGE_TWISTMODIFIED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3Stamped.h>
#include <geometry_msgs/Vector3Stamped.h>

namespace anafi_control
{
template <class ContainerAllocator>
struct TwistModified_
{
  typedef TwistModified_<ContainerAllocator> Type;

  TwistModified_()
    : linear()
    , angular()  {
    }
  TwistModified_(const ContainerAllocator& _alloc)
    : linear(_alloc)
    , angular(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3Stamped_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::geometry_msgs::Vector3Stamped_<ContainerAllocator>  _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::anafi_control::TwistModified_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anafi_control::TwistModified_<ContainerAllocator> const> ConstPtr;

}; // struct TwistModified_

typedef ::anafi_control::TwistModified_<std::allocator<void> > TwistModified;

typedef boost::shared_ptr< ::anafi_control::TwistModified > TwistModifiedPtr;
typedef boost::shared_ptr< ::anafi_control::TwistModified const> TwistModifiedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anafi_control::TwistModified_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anafi_control::TwistModified_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anafi_control::TwistModified_<ContainerAllocator1> & lhs, const ::anafi_control::TwistModified_<ContainerAllocator2> & rhs)
{
  return lhs.linear == rhs.linear &&
    lhs.angular == rhs.angular;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anafi_control::TwistModified_<ContainerAllocator1> & lhs, const ::anafi_control::TwistModified_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anafi_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anafi_control::TwistModified_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anafi_control::TwistModified_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anafi_control::TwistModified_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anafi_control::TwistModified_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anafi_control::TwistModified_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anafi_control::TwistModified_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anafi_control::TwistModified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d3ab5e2b924162f6809bed7c278f6b8";
  }

  static const char* value(const ::anafi_control::TwistModified_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d3ab5e2b924162fULL;
  static const uint64_t static_value2 = 0x6809bed7c278f6b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::anafi_control::TwistModified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anafi_control/TwistModified";
  }

  static const char* value(const ::anafi_control::TwistModified_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anafi_control::TwistModified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3Stamped linear\n"
"geometry_msgs/Vector3Stamped angular\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3Stamped\n"
"# This represents a Vector3 with reference coordinate frame and timestamp\n"
"Header header\n"
"Vector3 vector\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::anafi_control::TwistModified_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anafi_control::TwistModified_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwistModified_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anafi_control::TwistModified_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anafi_control::TwistModified_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3Stamped_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3Stamped_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANAFI_CONTROL_MESSAGE_TWISTMODIFIED_H
