// Generated by gencpp from file anafi_control/TwistStampedModified.msg
// DO NOT EDIT!


#ifndef ANAFI_CONTROL_MESSAGE_TWISTSTAMPEDMODIFIED_H
#define ANAFI_CONTROL_MESSAGE_TWISTSTAMPEDMODIFIED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <anafi_control/TwistModified.h>

namespace anafi_control
{
template <class ContainerAllocator>
struct TwistStampedModified_
{
  typedef TwistStampedModified_<ContainerAllocator> Type;

  TwistStampedModified_()
    : header()
    , twist()  {
    }
  TwistStampedModified_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , twist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::anafi_control::TwistModified_<ContainerAllocator>  _twist_type;
  _twist_type twist;





  typedef boost::shared_ptr< ::anafi_control::TwistStampedModified_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anafi_control::TwistStampedModified_<ContainerAllocator> const> ConstPtr;

}; // struct TwistStampedModified_

typedef ::anafi_control::TwistStampedModified_<std::allocator<void> > TwistStampedModified;

typedef boost::shared_ptr< ::anafi_control::TwistStampedModified > TwistStampedModifiedPtr;
typedef boost::shared_ptr< ::anafi_control::TwistStampedModified const> TwistStampedModifiedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anafi_control::TwistStampedModified_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anafi_control::TwistStampedModified_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anafi_control::TwistStampedModified_<ContainerAllocator1> & lhs, const ::anafi_control::TwistStampedModified_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.twist == rhs.twist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anafi_control::TwistStampedModified_<ContainerAllocator1> & lhs, const ::anafi_control::TwistStampedModified_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anafi_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anafi_control::TwistStampedModified_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anafi_control::TwistStampedModified_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anafi_control::TwistStampedModified_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anafi_control::TwistStampedModified_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anafi_control::TwistStampedModified_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anafi_control::TwistStampedModified_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anafi_control::TwistStampedModified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "953cf8d869ec497d6eb74723a9307a2e";
  }

  static const char* value(const ::anafi_control::TwistStampedModified_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x953cf8d869ec497dULL;
  static const uint64_t static_value2 = 0x6eb74723a9307a2eULL;
};

template<class ContainerAllocator>
struct DataType< ::anafi_control::TwistStampedModified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anafi_control/TwistStampedModified";
  }

  static const char* value(const ::anafi_control::TwistStampedModified_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anafi_control::TwistStampedModified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"anafi_control/TwistModified twist\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: anafi_control/TwistModified\n"
"geometry_msgs/Vector3Stamped linear\n"
"geometry_msgs/Vector3Stamped angular\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3Stamped\n"
"# This represents a Vector3 with reference coordinate frame and timestamp\n"
"Header header\n"
"Vector3 vector\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::anafi_control::TwistStampedModified_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anafi_control::TwistStampedModified_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwistStampedModified_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anafi_control::TwistStampedModified_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anafi_control::TwistStampedModified_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::anafi_control::TwistModified_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANAFI_CONTROL_MESSAGE_TWISTSTAMPEDMODIFIED_H
