(cl:in-package anafi_control-msg)
(cl:export '(HEADER-VAL
          HEADER
          REL_P_X-VAL
          REL_P_X
          REL_P_Y-VAL
          REL_P_Y
          REL_P_Z-VAL
          REL_P_Z
          REL_V_X-VAL
          REL_V_X
          REL_V_Y-VAL
          REL_V_Y
          REL_V_Z-VAL
          REL_V_Z
          REL_YAW-VAL
          REL_YAW
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          V_Z-VAL
          V_Z
          ROLL_RATE-VAL
          ROLL_RATE
          PITCH_RATE-VAL
          PITCH_RATE
          YAW_RATE-VAL
          YAW_RATE
))