# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from anafi_control/MultiRotorRelativeState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MultiRotorRelativeState(genpy.Message):
  _md5sum = "992f417326c3849f951a20961ff27171"
  _type = "anafi_control/MultiRotorRelativeState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float64 rel_p_x
float64 rel_p_y
float64 rel_p_z
float64 rel_v_x
float64 rel_v_y
float64 rel_v_z
float64 rel_yaw
float64 roll
float64 pitch
float64 yaw
float64 v_z
float64 roll_rate
float64 pitch_rate
float64 yaw_rate





================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','rel_p_x','rel_p_y','rel_p_z','rel_v_x','rel_v_y','rel_v_z','rel_yaw','roll','pitch','yaw','v_z','roll_rate','pitch_rate','yaw_rate']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,rel_p_x,rel_p_y,rel_p_z,rel_v_x,rel_v_y,rel_v_z,rel_yaw,roll,pitch,yaw,v_z,roll_rate,pitch_rate,yaw_rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MultiRotorRelativeState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.rel_p_x is None:
        self.rel_p_x = 0.
      if self.rel_p_y is None:
        self.rel_p_y = 0.
      if self.rel_p_z is None:
        self.rel_p_z = 0.
      if self.rel_v_x is None:
        self.rel_v_x = 0.
      if self.rel_v_y is None:
        self.rel_v_y = 0.
      if self.rel_v_z is None:
        self.rel_v_z = 0.
      if self.rel_yaw is None:
        self.rel_yaw = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.v_z is None:
        self.v_z = 0.
      if self.roll_rate is None:
        self.roll_rate = 0.
      if self.pitch_rate is None:
        self.pitch_rate = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.rel_p_x = 0.
      self.rel_p_y = 0.
      self.rel_p_z = 0.
      self.rel_v_x = 0.
      self.rel_v_y = 0.
      self.rel_v_z = 0.
      self.rel_yaw = 0.
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.v_z = 0.
      self.roll_rate = 0.
      self.pitch_rate = 0.
      self.yaw_rate = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.rel_p_x, _x.rel_p_y, _x.rel_p_z, _x.rel_v_x, _x.rel_v_y, _x.rel_v_z, _x.rel_yaw, _x.roll, _x.pitch, _x.yaw, _x.v_z, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.rel_p_x, _x.rel_p_y, _x.rel_p_z, _x.rel_v_x, _x.rel_v_y, _x.rel_v_z, _x.rel_yaw, _x.roll, _x.pitch, _x.yaw, _x.v_z, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_14d().pack(_x.rel_p_x, _x.rel_p_y, _x.rel_p_z, _x.rel_v_x, _x.rel_v_y, _x.rel_v_z, _x.rel_yaw, _x.roll, _x.pitch, _x.yaw, _x.v_z, _x.roll_rate, _x.pitch_rate, _x.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 112
      (_x.rel_p_x, _x.rel_p_y, _x.rel_p_z, _x.rel_v_x, _x.rel_v_y, _x.rel_v_z, _x.rel_yaw, _x.roll, _x.pitch, _x.yaw, _x.v_z, _x.roll_rate, _x.pitch_rate, _x.yaw_rate,) = _get_struct_14d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14d = None
def _get_struct_14d():
    global _struct_14d
    if _struct_14d is None:
        _struct_14d = struct.Struct("<14d")
    return _struct_14d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
