# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]

# standalone_tags:
#   [
#   {"id": 0, "size":0.07846},
#   {"id": 1, "size":0.07846},
#   {"id": 2, "size":0.07846},
#   {"id": 3, "size":0.07846},
#   {"id": 4, "size":0.07846},
#   {"id": 5, "size":0.07846},
#   ]
  

standalone_tags:
  [
  {"id": 0, "size":0.08},
  {"id": 1, "size":0.08},
  {"id": 2, "size":0.08},
  {"id": 3, "size":0.08},
  {"id": 4, "size":0.08},
  {"id": 5, "size":0.08},
  ]
    
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {"id": 0, "size": 0.08, "x": 0.05, "y": 0, "z": 0, "qw": 0.707, "qx": 0, "qy": 0.707, "qz": 0},
#           {"id": 1, "size": 0.08, "x": 0, "y": 0.05, "z": 0, "qw": 0.707, "qx": -0.707, "qy": 0, "qz": 0},
#           {"id": 2, "size": 0.08, "x": -0.05, "y": 0, "z": 0, "qw": 0.707, "qx": 0, "qy": -0.707, "qz": 0},
#           {"id": 3, "size": 0.08, "x": 0, "y": -0.05, "z": 0, "qw": 0.707, "qx": 0.707, "qy": 0, "qz": 0},
#           {"id": 4, "size": 0.08, "x": 0, "y": 0, "z": -0.05, "qw": 0, "qx": 0, "qy": 0, "qz": 1},
#           {"id": 5, "size": 0.08, "x": 0, "y": 0, "z": 0.05, "qw": 0, "qx": 0, "qy": 0, "qz": 0}
#         ]
#     }
#   ]
# tag_bundles:
#   [
#   {"id": 0, "size": 0.08, "x": 0, "y": -0.05, "z": 0, "qw": 0.707, "qx": 0, "qy": 0.707, "qz": 0},
#   {"id": 1, "size": 0.08, "x": -0.05, "y": 0, "z": 0, "qw": 0.707, "qx": -0.707, "qy": 0, "qz": 0},
#   {"id": 2, "size": 0.08, "x": 0, "y": 0.05, "z": 0, "qw": 0.707, "qx": 0, "qy": -0.707, "qz": 0},
#   {"id": 3, "size": 0.08, "x": 0.05, "y": 0, "z": 0, "qw": 0.707, "qx": 0.707, "qy": 0, "qz": 0},
#   {"id": 4, "size": 0.08, "x": 0, "y": 0, "z": 0.05, "qw": 0, "qx": 0, "qy": 0, "qz": 1},
#   {"id": 5, "size": 0.08, "x": 0, "y": 0, "z": -0.05, "qw": 0, "qx": 0, "qy": 0, "qz": 0}
#   ]
